title: Homepage
page-top-title: Homepage
top-section-bg-text: Ground Truth Lab
home-subtitle: Guorui Chen&ensp;|&ensp;陈国瑞
copyright-text: '&copy; Guorui Chen 2023-2025. All Rights Reserved.'

site_name: Guorui Chen
site_description: Large Language Model; 
email: GuoRuiC@outlook.com